### ISSUE TITLE
How/where do you run your Gulp to get them in the container

### ISSUE THREAD

**Issue by mvaneijgen** [ipunkt/docker-gulp-tasks#60]
I have a set of Gulp tasks I always use for a project and I am trying to switch over to Docker to have them run detached from my host machine. So all my tasks are already the way I want them to be, but how do you run your Gulp command (mine are `gulp`, `gulp watch` and `gulp --production`) inside the container, if I run them from the command line Gulp is used from my host machine, which is not what I want I just want to run my `docker-compose.yml` file and have it all run from there, but I need to some how specify the location of my `gulpfile.js`  so that Docker knows where the start point is of my project. 

If it helps my setup is for Wordpress theme development and [my `docker-compose.yml` file looks like this](https://gist.github.com/mvaneijgen/7088fa56d91bd8a7d77f9629ea89e791), there is no npm, gulp or bower installed at the moment, because I am just plain lost. To get this file working I spend the better part of my weekend setting it up and now I am lost. I mount the root locations of a Wordpress install, so I need to have Gulp run inside that mount, but a few folders deeper inside `/wp-content/themes/MY-THEME` because there my `package.json`, `gulpfile.js` and `bower.json` files are stored. Could you shed any light on this matter or some location on where I could find detailed information to set it up?

Sorry to bother you and if this is the wrong place to ask just close this issue.

**Comment by justb81** [comment]
@mvaneijgen do you use our container for gulp processing? Maybe, you just forgot the `./` before `gulp` to exec the local command and not the global one.

**Comment by mvaneijgen** [comment]
I tried using your container for Gulp processing, but I am lost on how to make it so that it uses my own Gulp task and how to set the location of these files.

I need a container with NPM, Gulp and Bower installed and have it compile my files that are exposed via the Wordpress image inside the 
```
volumes:
      - ./:/var/www/html
```

I think I some how need to change the ENV tag in your Docerfile https://github.com/ipunkt/docker-gulp-tasks/blob/a36e14091bd443afc11e6b4faf4d5f1ffb0e9a92/Dockerfile#L32 but I don't know where to start of what to search for to get a better understanding how to create a Dockerfile my self that works with my own tasks
